### ISSUE TITLE
All Checkpoints, remove feedback

### ISSUE THREAD

**Issue by snychka** [ps-interactive/asp-net-core-6-fundamentals#41]
From all Checkpoints, remove feedback (see [What are the recommended layout and settings for a Checkpoint?](https://docs.google.com/document/d/1kmko29RHzusIBqZolIJGnlzlyMBzjbm2HX-NSFnAYAI/edit#bookmark=id.w9x785qwyi8l) in the FAQ)
<img width="853" alt="Screen Shot 2022-11-20 at 7 51 37 PM" src="https://user-images.githubusercontent.com/5722849/202953069-1693541d-8d27-478a-b3a4-17f69423f802.png">

- [x] Checkpoint 01-13 (update: [~~Stefan will do!~~ done!](https://psauthors.slack.com/archives/C02PCSL6082/p1669065498755379)!)
- [ ] Checkpoint 14-27

Feel free to assign me half of the Checkpoints! @ me in slack, here, and assign this to me along with you, if so.

**Comment by snychka** [comment]
@GillCleeren , done the first half. Please do the 2nd half, and do ask if you have any questions

**Comment by GillCleeren** [comment]
Done

**Comment by snychka** [comment]
Hey @GillCleeren, re-opening, as you still need to toggle off Share Checks for cp 14-27. See the screenshot above!

**Comment by GillCleeren** [comment]
Done @snychka
